/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AdvancedType, SlideValue, } from "./types/sloth-component";
export namespace Components {
    interface SlothComponent {
        "advanced": AdvancedType;
        "max": number;
        "min": number;
        "value"?: string | null;
    }
}
declare global {
    interface HTMLSlothComponentElement extends Components.SlothComponent, HTMLStencilElement {
    }
    var HTMLSlothComponentElement: {
        prototype: HTMLSlothComponentElement;
        new (): HTMLSlothComponentElement;
    };
    interface HTMLElementTagNameMap {
        "sloth-component": HTMLSlothComponentElement;
    }
}
declare namespace LocalJSX {
    interface SlothComponent {
        "advanced"?: AdvancedType;
        "max"?: number;
        "min"?: number;
        "onSlideChanged"?: (event: CustomEvent<SlideValue>) => void;
        "value"?: string | null;
    }
    interface IntrinsicElements {
        "sloth-component": SlothComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sloth-component": LocalJSX.SlothComponent & JSXBase.HTMLAttributes<HTMLSlothComponentElement>;
        }
    }
}
